//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCME.Linker.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCME.Linker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Element applicability {0} {1}.
        /// </summary>
        public static string Applicability {
            get {
                return ResourceManager.GetString("Applicability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Assembly.
        /// </summary>
        public static string Assembly {
            get {
                return ResourceManager.GetString("Assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An assembly with this serial number already exists..
        /// </summary>
        public static string AssemblyExists {
            get {
                return ResourceManager.GetString("AssemblyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authenticate.
        /// </summary>
        public static string Authenticate {
            get {
                return ResourceManager.GetString("Authenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authentication.
        /// </summary>
        public static string Authentication {
            get {
                return ResourceManager.GetString("Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By GroupName list.
        /// </summary>
        public static string ByGroupNameList {
            get {
                return ResourceManager.GetString("ByGroupNameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By package serial num.
        /// </summary>
        public static string ByPackageSerialNum {
            get {
                return ResourceManager.GetString("ByPackageSerialNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total links {0} {1}.
        /// </summary>
        public static string CreatedLinksTotal {
            get {
                return ResourceManager.GetString("CreatedLinksTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create links between elements and packages.
        /// </summary>
        public static string CreateLinksBetweenElementsAndPackages {
            get {
                return ResourceManager.GetString("CreateLinksBetweenElementsAndPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description have wrong format.
        /// </summary>
        public static string DescriptionWrongFormat {
            get {
                return ResourceManager.GetString("DescriptionWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Semiconductor element with this number was assembled earlier. You cannot reuse semiconductor element with this number..
        /// </summary>
        public static string DeviceCodeisUsed {
            get {
                return ResourceManager.GetString("DeviceCodeisUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Element.
        /// </summary>
        public static string Element {
            get {
                return ResourceManager.GetString("Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Element2.
        /// </summary>
        public static string Element2 {
            get {
                return ResourceManager.GetString("Element2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No.
        /// </summary>
        public static string FalseToString {
            get {
                return ResourceManager.GetString("FalseToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GroupName.
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GroupName is not valid.
        /// </summary>
        public static string GroupNameIsNotValid {
            get {
                return ResourceManager.GetString("GroupNameIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GroupName not selected. Please select GroupName..
        /// </summary>
        public static string GroupNameNotSelected {
            get {
                return ResourceManager.GetString("GroupNameNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LastTimeStamp.
        /// </summary>
        public static string LastTS {
            get {
                return ResourceManager.GetString("LastTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Links count.
        /// </summary>
        public static string LinksCount {
            get {
                return ResourceManager.GetString("LinksCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The data list was not created.
        /// </summary>
        public static string ListDataNotCreated {
            get {
                return ResourceManager.GetString("ListDataNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not issued from the lots: {0} to job &apos;{1}&apos;..
        /// </summary>
        public static string LotNotIssuedToJob {
            get {
                return ResourceManager.GetString("LotNotIssuedToJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Manual entry a Job.
        /// </summary>
        public static string ManualEntryGroupName {
            get {
                return ResourceManager.GetString("ManualEntryGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Manual entry a package.
        /// </summary>
        public static string ManualEntryPackage {
            get {
                return ResourceManager.GetString("ManualEntryPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Package (new).
        /// </summary>
        public static string NewPackage {
            get {
                return ResourceManager.GetString("NewPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No data.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Old serial number.
        /// </summary>
        public static string OldSerialNum {
            get {
                return ResourceManager.GetString("OldSerialNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Old serial number is not found..
        /// </summary>
        public static string OldSerialNumIsNotFound {
            get {
                return ResourceManager.GetString("OldSerialNumIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Operation error.
        /// </summary>
        public static string OperationError {
            get {
                return ResourceManager.GetString("OperationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Package.
        /// </summary>
        public static string Package {
            get {
                return ResourceManager.GetString("Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The password is incorrect.
        /// </summary>
        public static string PasswordIncorrect {
            get {
                return ResourceManager.GetString("PasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The password is incorrect or the DC user &apos;{0}&apos; does not exist.
        /// </summary>
        public static string PasswordIsIncorrect {
            get {
                return ResourceManager.GetString("PasswordIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на pieces.
        /// </summary>
        public static string Pieces {
            get {
                return ResourceManager.GetString("Pieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quantity released by Job {0} {1}.
        /// </summary>
        public static string QtyReleased {
            get {
                return ResourceManager.GetString("QtyReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error in the implementation of &apos;{0}&apos;. Contact the developer.
        /// </summary>
        public static string RealisationError {
            get {
                return ResourceManager.GetString("RealisationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Relabeling.
        /// </summary>
        public static string Relabeling {
            get {
                return ResourceManager.GetString("Relabeling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Selecting a way to search a GroupName.
        /// </summary>
        public static string SelectingWayToSearchGroupName {
            get {
                return ResourceManager.GetString("SelectingWayToSearchGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Serial number.
        /// </summary>
        public static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Package serial number is not valid. It is already used..
        /// </summary>
        public static string SerialNumIsNotValid {
            get {
                return ResourceManager.GetString("SerialNumIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set value.
        /// </summary>
        public static string SetValue {
            get {
                return ResourceManager.GetString("SetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shown links count {0} of {1} {2}.
        /// </summary>
        public static string ShownLinksCount {
            get {
                return ResourceManager.GetString("ShownLinksCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Statistics by jobs.
        /// </summary>
        public static string StatisticsByJobs {
            get {
                return ResourceManager.GetString("StatisticsByJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes.
        /// </summary>
        public static string TrueToString {
            get {
                return ResourceManager.GetString("TrueToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DateTimeStamp.
        /// </summary>
        public static string TS {
            get {
                return ResourceManager.GetString("TS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Assembler.
        /// </summary>
        public static string UserAssembler {
            get {
                return ResourceManager.GetString("UserAssembler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User credentials.
        /// </summary>
        public static string UserCredentials {
            get {
                return ResourceManager.GetString("UserCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User &apos;{0}&apos; is not an application user &apos;{1}&apos;.
        /// </summary>
        public static string UserIisNotAnApplicationUser {
            get {
                return ResourceManager.GetString("UserIisNotAnApplicationUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The value is not a number..
        /// </summary>
        public static string ValueIsNotInteger {
            get {
                return ResourceManager.GetString("ValueIsNotInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value out of range. Valid values ​​are defined in system 0502 &apos;Print Labels&apos;..
        /// </summary>
        public static string ValueOutOfRange {
            get {
                return ResourceManager.GetString("ValueOutOfRange", resourceCulture);
            }
        }
    }
}
