//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCME.dbViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCME.dbViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Allowed number of characters.
        /// </summary>
        public static string AllowedNumberOfCharacters {
            get {
                return ResourceManager.GetString("AllowedNumberOfCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Assembly job.
        /// </summary>
        public static string AssemblyJob {
            get {
                return ResourceManager.GetString("AssemblyJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Assembly protocol.
        /// </summary>
        public static string AssemblyProtocol {
            get {
                return ResourceManager.GetString("AssemblyProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Assembly protocols.
        /// </summary>
        public static string AssemblyProtocols {
            get {
                return ResourceManager.GetString("AssemblyProtocols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на State.
        /// </summary>
        public static string AssemblyStatusDescr {
            get {
                return ResourceManager.GetString("AssemblyStatusDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authenticate.
        /// </summary>
        public static string Authenticate {
            get {
                return ResourceManager.GetString("Authenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authentication.
        /// </summary>
        public static string Authentication {
            get {
                return ResourceManager.GetString("Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ITAV.
        /// </summary>
        public static string AverageCurrent {
            get {
                return ResourceManager.GetString("AverageCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To begin.
        /// </summary>
        public static string Begin {
            get {
                return ResourceManager.GetString("Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Manage user permissions.
        /// </summary>
        public static string BitCalculator {
            get {
                return ResourceManager.GetString("BitCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Build.
        /// </summary>
        public static string Build {
            get {
                return ResourceManager.GetString("Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The previously saved list will be loaded from the database instead of the displayed list. Proceed?.
        /// </summary>
        public static string CanReloadList {
            get {
                return ResourceManager.GetString("CanReloadList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Case type.
        /// </summary>
        public static string CaseType {
            get {
                return ResourceManager.GetString("CaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change prohibited.
        /// </summary>
        public static string ChangeProhibited {
            get {
                return ResourceManager.GetString("ChangeProhibited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Checked.
        /// </summary>
        public static string CheckedDevice {
            get {
                return ResourceManager.GetString("CheckedDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check value of.
        /// </summary>
        public static string CheckValue {
            get {
                return ResourceManager.GetString("CheckValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Climatic.
        /// </summary>
        public static string Climatic {
            get {
                return ResourceManager.GetString("Climatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Subject num.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Code of non match.
        /// </summary>
        public static string CodeOfNonMatch {
            get {
                return ResourceManager.GetString("CodeOfNonMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Test conditions.
        /// </summary>
        public static string ConditionsOfTest {
            get {
                return ResourceManager.GetString("ConditionsOfTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameter &apos;{0}&apos; and all its saved values ​​will be permanently deleted. Proceed?.
        /// </summary>
        public static string ConfirmationMessForDeleteManualInputParam {
            get {
                return ResourceManager.GetString("ConfirmationMessForDeleteManualInputParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Constr..
        /// </summary>
        public static string Constructive {
            get {
                return ResourceManager.GetString("Constructive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create assembly protocol.
        /// </summary>
        public static string CreateAssemblyProtocol {
            get {
                return ResourceManager.GetString("CreateAssemblyProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create devices.
        /// </summary>
        public static string CreateDevices {
            get {
                return ResourceManager.GetString("CreateDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create parameter.
        /// </summary>
        public static string CreateParameter {
            get {
                return ResourceManager.GetString("CreateParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create value of manually entered parameter.
        /// </summary>
        public static string CreateValueOfManuallyEnteredParameter {
            get {
                return ResourceManager.GetString("CreateValueOfManuallyEnteredParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current profile.
        /// </summary>
        public static string CurrentProfile {
            get {
                return ResourceManager.GetString("CurrentProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cut.
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The entered data contains an error..
        /// </summary>
        public static string DataContainsAnError {
            get {
                return ResourceManager.GetString("DataContainsAnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data loading failed.
        /// </summary>
        public static string DataLoadingFailed {
            get {
                return ResourceManager.GetString("DataLoadingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data will not be saved..
        /// </summary>
        public static string DataWillNotBeSaved {
            get {
                return ResourceManager.GetString("DataWillNotBeSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date created.
        /// </summary>
        public static string DateCreated {
            get {
                return ResourceManager.GetString("DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete all filters.
        /// </summary>
        public static string DeleteAllFilters {
            get {
                return ResourceManager.GetString("DeleteAllFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The system rejected the delete operation. The number of references to the deletion object is greater than zero..
        /// </summary>
        public static string DeleteCancelled {
            get {
                return ResourceManager.GetString("DeleteCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete column.
        /// </summary>
        public static string DeleteColumn {
            get {
                return ResourceManager.GetString("DeleteColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete record.
        /// </summary>
        public static string DeleteCurrentRecord {
            get {
                return ResourceManager.GetString("DeleteCurrentRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Deleted.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete parameter.
        /// </summary>
        public static string DeleteParameter {
            get {
                return ResourceManager.GetString("DeleteParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete permissions of user.
        /// </summary>
        public static string DeletePermissionsOfUser {
            get {
                return ResourceManager.GetString("DeletePermissionsOfUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete selected records.
        /// </summary>
        public static string DeleteSelectedRecords {
            get {
                return ResourceManager.GetString("DeleteSelectedRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete value of manually entered parameter.
        /// </summary>
        public static string DeleteValueOfManuallyEnteredParameter {
            get {
                return ResourceManager.GetString("DeleteValueOfManuallyEnteredParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description in english.
        /// </summary>
        public static string DescrEN {
            get {
                return ResourceManager.GetString("DescrEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description of device parameters.
        /// </summary>
        public static string DescriptionOfDeviceParameters {
            get {
                return ResourceManager.GetString("DescriptionOfDeviceParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description in russian.
        /// </summary>
        public static string DescrRU {
            get {
                return ResourceManager.GetString("DescrRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Destroy.
        /// </summary>
        public static string Destroy {
            get {
                return ResourceManager.GetString("Destroy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Class.
        /// </summary>
        public static string DeviceClass {
            get {
                return ResourceManager.GetString("DeviceClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Comments.
        /// </summary>
        public static string DeviceComments {
            get {
                return ResourceManager.GetString("DeviceComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Measurement group comments.
        /// </summary>
        public static string DeviceCommentsOneString {
            get {
                return ResourceManager.GetString("DeviceCommentsOneString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Device parameters.
        /// </summary>
        public static string DeviceParameters {
            get {
                return ResourceManager.GetString("DeviceParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Device reference editor.
        /// </summary>
        public static string DeviceReferenceEditor {
            get {
                return ResourceManager.GetString("DeviceReferenceEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на References of devices norms.
        /// </summary>
        public static string DeviceReferences {
            get {
                return ResourceManager.GetString("DeviceReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Devices.
        /// </summary>
        public static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type.
        /// </summary>
        public static string DeviceType {
            get {
                return ResourceManager.GetString("DeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type EN.
        /// </summary>
        public static string DeviceTypeEN {
            get {
                return ResourceManager.GetString("DeviceTypeEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type RU.
        /// </summary>
        public static string DeviceTypeRU {
            get {
                return ResourceManager.GetString("DeviceTypeRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Device identificator.
        /// </summary>
        public static string DevID {
            get {
                return ResourceManager.GetString("DevID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The temperature mode of the displayed parameters and the selected profile do not match..
        /// </summary>
        public static string DifferentTemperatureModes {
            get {
                return ResourceManager.GetString("DifferentTemperatureModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на does not exist.
        /// </summary>
        public static string DoesNotExist {
            get {
                return ResourceManager.GetString("DoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на dU/dt.
        /// </summary>
        public static string dUdt {
            get {
                return ResourceManager.GetString("dUdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на dU/dtMin.
        /// </summary>
        public static string dUdtMin {
            get {
                return ResourceManager.GetString("dUdtMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Linker: Edit assembly.
        /// </summary>
        public static string EditAssembly {
            get {
                return ResourceManager.GetString("EditAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit parameter.
        /// </summary>
        public static string EditParameter {
            get {
                return ResourceManager.GetString("EditParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit value of manually entered parameter.
        /// </summary>
        public static string EditValueOfManuallyEnteredParameter {
            get {
                return ResourceManager.GetString("EditValueOfManuallyEnteredParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The system prevented the creation of a column for an empty list of records..
        /// </summary>
        public static string ErrorCreateColumnByListOfRecordsIsEmpty {
            get {
                return ResourceManager.GetString("ErrorCreateColumnByListOfRecordsIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to create.
        /// </summary>
        public static string FailedToCreate {
            get {
                return ResourceManager.GetString("FailedToCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filter comparison type is not &apos;=&apos;..
        /// </summary>
        public static string FilterComparisonTypeIsNotEqual {
            get {
                return ResourceManager.GetString("FilterComparisonTypeIsNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filter by field &quot;{0}&quot; is off..
        /// </summary>
        public static string FilterIsNotOn {
            get {
                return ResourceManager.GetString("FilterIsNotOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The number of filters on the field &quot;{0}&quot; is not equal to 1. To perform this action, no more than one filter on the field &quot;{0}&quot; is required..
        /// </summary>
        public static string FilterIsNotSingle {
            get {
                return ResourceManager.GetString("FilterIsNotSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The number of actived filters is not equal to 1. Only one filter is required to perform this action..
        /// </summary>
        public static string FiltersCountIsNotOne {
            get {
                return ResourceManager.GetString("FiltersCountIsNotOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The value of filter &apos;{0}&apos; is not equal &apos;{1}&apos;..
        /// </summary>
        public static string FilterValueIsBad {
            get {
                return ResourceManager.GetString("FilterValueIsBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The number of filter values ​​for the field &quot;{0}&quot; is not equal to 1. To perform this action, no more than one filter value for the field &quot;{0}&quot; is required..
        /// </summary>
        public static string FilterValuesIsNotSingle {
            get {
                return ResourceManager.GetString("FilterValuesIsNotSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Job.
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IdrmMax.
        /// </summary>
        public static string IdrmMax {
            get {
                return ResourceManager.GetString("IdrmMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IgtMax.
        /// </summary>
        public static string IgtMax {
            get {
                return ResourceManager.GetString("IgtMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на In assembly protocol.
        /// </summary>
        public static string InAssemblyProtocol {
            get {
                return ResourceManager.GetString("InAssemblyProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IrrmMax.
        /// </summary>
        public static string IrrmMax {
            get {
                return ResourceManager.GetString("IrrmMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Item.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на List of assembly protocols.
        /// </summary>
        public static string ListOfAssemblyProtocols {
            get {
                return ResourceManager.GetString("ListOfAssemblyProtocols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error loading data from database.
        /// </summary>
        public static string LoadDataFromDataBaseFault {
            get {
                return ResourceManager.GetString("LoadDataFromDataBaseFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Work with the data collected by means of MME hardware in the central database..
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Manage by self permissions.
        /// </summary>
        public static string ManageBySelfPermissions {
            get {
                return ResourceManager.GetString("ManageBySelfPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Manage device references.
        /// </summary>
        public static string ManageDeviceReferences {
            get {
                return ResourceManager.GetString("ManageDeviceReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Manage permissions of user.
        /// </summary>
        public static string ManagePermissionsOfUser {
            get {
                return ResourceManager.GetString("ManagePermissionsOfUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Manual add devices.
        /// </summary>
        public static string ManualAddDevices {
            get {
                return ResourceManager.GetString("ManualAddDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Manual entry profile.
        /// </summary>
        public static string ManualEntryProfile {
            get {
                return ResourceManager.GetString("ManualEntryProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Manual input param editor.
        /// </summary>
        public static string ManualInputParamEditor {
            get {
                return ResourceManager.GetString("ManualInputParamEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Manually entered parameters.
        /// </summary>
        public static string ManualInputParams {
            get {
                return ResourceManager.GetString("ManualInputParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Middle name.
        /// </summary>
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Code MME.
        /// </summary>
        public static string MmeCode {
            get {
                return ResourceManager.GetString("MmeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mode view.
        /// </summary>
        public static string ModeView {
            get {
                return ResourceManager.GetString("ModeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mod..
        /// </summary>
        public static string Modification {
            get {
                return ResourceManager.GetString("Modification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The parameter cannot be selected. The value of a parameter with the same name already exists in the editing object..
        /// </summary>
        public static string NameAlreadyExistsInObject {
            get {
                return ResourceManager.GetString("NameAlreadyExistsInObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No data.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No editing object selected..
        /// </summary>
        public static string NoEditingObjectSelected {
            get {
                return ResourceManager.GetString("NoEditingObjectSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No filters installed. Install at least one filter..
        /// </summary>
        public static string NoFiltersInstalled {
            get {
                return ResourceManager.GetString("NoFiltersInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No permission for this action..
        /// </summary>
        public static string NoPermissions {
            get {
                return ResourceManager.GetString("NoPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max value of norms.
        /// </summary>
        public static string NormMaxValue {
            get {
                return ResourceManager.GetString("NormMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Min value of norms.
        /// </summary>
        public static string NormMinValue {
            get {
                return ResourceManager.GetString("NormMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not created by hand.
        /// </summary>
        public static string NotCreatedByHand {
            get {
                return ResourceManager.GetString("NotCreatedByHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &apos;{0}&apos;  not found in SyteLine..
        /// </summary>
        public static string NotFoundInSL {
            get {
                return ResourceManager.GetString("NotFoundInSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ничего не было выбрано..
        /// </summary>
        public static string NothingHasBeenSelected {
            get {
                return ResourceManager.GetString("NothingHasBeenSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not in assembly protocol.
        /// </summary>
        public static string NotInAssemblyProtocol {
            get {
                return ResourceManager.GetString("NotInAssemblyProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на not setted.
        /// </summary>
        public static string NotSetted {
            get {
                return ResourceManager.GetString("NotSetted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Object for delete not selected..
        /// </summary>
        public static string ObjectForDeleteNotSelected {
            get {
                return ResourceManager.GetString("ObjectForDeleteNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Omnity.
        /// </summary>
        public static string Omnity {
            get {
                return ResourceManager.GetString("Omnity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Operation failed.
        /// </summary>
        public static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Out of range.
        /// </summary>
        public static string OutOfRange {
            get {
                return ResourceManager.GetString("OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameter name not defined..
        /// </summary>
        public static string ParameterNameNotDefined {
            get {
                return ResourceManager.GetString("ParameterNameNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameters.
        /// </summary>
        public static string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Paremeter &apos;{0}&apos; is in use. The parameter can only be used once..
        /// </summary>
        public static string ParemeterIsInUse {
            get {
                return ResourceManager.GetString("ParemeterIsInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The password is incorrect.
        /// </summary>
        public static string PasswordIncorrect {
            get {
                return ResourceManager.GetString("PasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The password is incorrect or the DC user &apos;{0}&apos; does not exist.
        /// </summary>
        public static string PasswordIsIncorrect {
            get {
                return ResourceManager.GetString("PasswordIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Paste.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please authenticate..
        /// </summary>
        public static string PleaseAuthenticate {
            get {
                return ResourceManager.GetString("PleaseAuthenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Processed record count {0}.
        /// </summary>
        public static string ProcessedRecordCount {
            get {
                return ResourceManager.GetString("ProcessedRecordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на For {0} processing is not provided..
        /// </summary>
        public static string ProcessingIsNotProvided {
            get {
                return ResourceManager.GetString("ProcessingIsNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Body of profile.
        /// </summary>
        public static string ProfileBody {
            get {
                return ResourceManager.GetString("ProfileBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profile description.
        /// </summary>
        public static string ProfileDescription {
            get {
                return ResourceManager.GetString("ProfileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profile identificator.
        /// </summary>
        public static string ProfileID {
            get {
                return ResourceManager.GetString("ProfileID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profile name.
        /// </summary>
        public static string ProfileName {
            get {
                return ResourceManager.GetString("ProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profile of displayed data.
        /// </summary>
        public static string ProfileOfDisplayedData {
            get {
                return ResourceManager.GetString("ProfileOfDisplayedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Protocol num.
        /// </summary>
        public static string ProtocolDescr {
            get {
                return ResourceManager.GetString("ProtocolDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PrsmMin.
        /// </summary>
        public static string PrsmMin {
            get {
                return ResourceManager.GetString("PrsmMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Qrr.
        /// </summary>
        public static string Qrr {
            get {
                return ResourceManager.GetString("Qrr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на QrrMax.
        /// </summary>
        public static string QrrMax {
            get {
                return ResourceManager.GetString("QrrMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quant..
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Read and create comment.
        /// </summary>
        public static string ReadCreateComment {
            get {
                return ResourceManager.GetString("ReadCreateComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reading comments.
        /// </summary>
        public static string ReadingComments {
            get {
                return ResourceManager.GetString("ReadingComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reading the value of the &apos;Reason&apos; field.
        /// </summary>
        public static string ReadReason {
            get {
                return ResourceManager.GetString("ReadReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reason.
        /// </summary>
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Record date.
        /// </summary>
        public static string RecordDate {
            get {
                return ResourceManager.GetString("RecordDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Records:.
        /// </summary>
        public static string Records {
            get {
                return ResourceManager.GetString("Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Record successfully deleted.
        /// </summary>
        public static string RecordSuccessfullyDeleted {
            get {
                return ResourceManager.GetString("RecordSuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на References.
        /// </summary>
        public static string References {
            get {
                return ResourceManager.GetString("References", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refresh   F5.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An error was found in the source data for building the report. Reason {0}..
        /// </summary>
        public static string ReportBuildingError {
            get {
                return ResourceManager.GetString("ReportBuildingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The source data for building a report is empty. Report generation does not make sense..
        /// </summary>
        public static string ReportCannotBeGenerated {
            get {
                return ResourceManager.GetString("ReportCannotBeGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RisolMin.
        /// </summary>
        public static string RisolMin {
            get {
                return ResourceManager.GetString("RisolMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save failed..
        /// </summary>
        public static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save was successful..
        /// </summary>
        public static string SaveWasSuccessful {
            get {
                return ResourceManager.GetString("SaveWasSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select all records shown.
        /// </summary>
        public static string SelectAllRecords {
            get {
                return ResourceManager.GetString("SelectAllRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select by number of records.
        /// </summary>
        public static string SelectByNumberOfRecords {
            get {
                return ResourceManager.GetString("SelectByNumberOfRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select DC user.
        /// </summary>
        public static string SelectDCUser {
            get {
                return ResourceManager.GetString("SelectDCUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Selected data is not for change..
        /// </summary>
        public static string SelectedDataIsNotForChange {
            get {
                return ResourceManager.GetString("SelectedDataIsNotForChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The selected parameter &apos;{0}&apos; is not deletable..
        /// </summary>
        public static string SelectedParameterIsNotDeletable {
            get {
                return ResourceManager.GetString("SelectedParameterIsNotDeletable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The selected parameter &apos;{0}&apos; is not editable. The value of this parameter can be obtained by measuring on equipment..
        /// </summary>
        public static string SelectedParameterIsNotEditable {
            get {
                return ResourceManager.GetString("SelectedParameterIsNotEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Selected profile.
        /// </summary>
        public static string SelectedProfile {
            get {
                return ResourceManager.GetString("SelectedProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Selected profile parameters:.
        /// </summary>
        public static string SelectedProfileParameters {
            get {
                return ResourceManager.GetString("SelectedProfileParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Selected records deleted successfully..
        /// </summary>
        public static string SelectedRecordsDeletedSuccessfully {
            get {
                return ResourceManager.GetString("SelectedRecordsDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Selected measurement groups was successfully moved to assembly protocol № {0}..
        /// </summary>
        public static string SelectedSuccessfullySendedToAssemblyProtocol {
            get {
                return ResourceManager.GetString("SelectedSuccessfullySendedToAssemblyProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Selected to initialization state.
        /// </summary>
        public static string SelectedToInitState {
            get {
                return ResourceManager.GetString("SelectedToInitState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select job.
        /// </summary>
        public static string SelectGroupName {
            get {
                return ResourceManager.GetString("SelectGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select profile.
        /// </summary>
        public static string SelectProfile {
            get {
                return ResourceManager.GetString("SelectProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send selected measurement groups to assembly protocol №.
        /// </summary>
        public static string SendSelectedToAssemblyProtocol {
            get {
                return ResourceManager.GetString("SendSelectedToAssemblyProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Session.
        /// </summary>
        public static string Session {
            get {
                return ResourceManager.GetString("Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set user as admin.
        /// </summary>
        public static string SetAdministrator {
            get {
                return ResourceManager.GetString("SetAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set assembly protocol mode on.
        /// </summary>
        public static string SetAssemblyProtocolModeOn {
            get {
                return ResourceManager.GetString("SetAssemblyProtocolModeOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set comment for measurement group.
        /// </summary>
        public static string SetCommentForMeasurementGroup {
            get {
                return ResourceManager.GetString("SetCommentForMeasurementGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set user permissions.
        /// </summary>
        public static string SetUserPermissions {
            get {
                return ResourceManager.GetString("SetUserPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Omnity.
        /// </summary>
        public static string SiOmnity {
            get {
                return ResourceManager.GetString("SiOmnity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Si.
        /// </summary>
        public static string SiType {
            get {
                return ResourceManager.GetString("SiType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Assembly.
        /// </summary>
        public static string StateAssembly {
            get {
                return ResourceManager.GetString("StateAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Initialization.
        /// </summary>
        public static string StateInitialization {
            get {
                return ResourceManager.GetString("StateInitialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Assembly status.
        /// </summary>
        public static string StatusByAssemblyProtocol {
            get {
                return ResourceManager.GetString("StatusByAssemblyProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The &quot;{0}&quot; is {1}. Enter value of &quot;{0}&quot;..
        /// </summary>
        public static string SubjectNotSetted {
            get {
                return ResourceManager.GetString("SubjectNotSetted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Condition of temperature.
        /// </summary>
        public static string TemperatureCondition {
            get {
                return ResourceManager.GetString("TemperatureCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на tgt.
        /// </summary>
        public static string tgt {
            get {
                return ResourceManager.GetString("tgt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TgtMax.
        /// </summary>
        public static string TgtMax {
            get {
                return ResourceManager.GetString("TgtMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TjMax.
        /// </summary>
        public static string TjMax {
            get {
                return ResourceManager.GetString("TjMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на tq.
        /// </summary>
        public static string tq {
            get {
                return ResourceManager.GetString("tq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TqMin.
        /// </summary>
        public static string TqMin {
            get {
                return ResourceManager.GetString("TqMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на trr.
        /// </summary>
        public static string trr {
            get {
                return ResourceManager.GetString("trr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TrrMin.
        /// </summary>
        public static string TrrMin {
            get {
                return ResourceManager.GetString("TrrMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date.
        /// </summary>
        public static string Ts {
            get {
                return ResourceManager.GetString("Ts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UbrMin.
        /// </summary>
        public static string UbrMin {
            get {
                return ResourceManager.GetString("UbrMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UdsmMin.
        /// </summary>
        public static string UdsmMin {
            get {
                return ResourceManager.GetString("UdsmMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UfmMax.
        /// </summary>
        public static string UfmMax {
            get {
                return ResourceManager.GetString("UfmMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UgtMax.
        /// </summary>
        public static string UgtMax {
            get {
                return ResourceManager.GetString("UgtMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UisolMin.
        /// </summary>
        public static string UisolMin {
            get {
                return ResourceManager.GetString("UisolMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Um.
        /// </summary>
        public static string Um {
            get {
                return ResourceManager.GetString("Um", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unit measure is not defined..
        /// </summary>
        public static string UnitMeasureIsNotDefined {
            get {
                return ResourceManager.GetString("UnitMeasureIsNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Temperature condition is unknown.
        /// </summary>
        public static string UnknownTemperatureCondition {
            get {
                return ResourceManager.GetString("UnknownTemperatureCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Uncheck the all records shown.
        /// </summary>
        public static string UnSelectAllRecords {
            get {
                return ResourceManager.GetString("UnSelectAllRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UrsmMin.
        /// </summary>
        public static string UrsmMin {
            get {
                return ResourceManager.GetString("UrsmMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User credentials.
        /// </summary>
        public static string UserCredentials {
            get {
                return ResourceManager.GetString("UserCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User &apos;{0}&apos; is not an application user &apos;{1}&apos;.
        /// </summary>
        public static string UserIisNotAnApplicationUser {
            get {
                return ResourceManager.GetString("UserIisNotAnApplicationUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User selected.
        /// </summary>
        public static string UserSelected {
            get {
                return ResourceManager.GetString("UserSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Operator.
        /// </summary>
        public static string Usr {
            get {
                return ResourceManager.GetString("Usr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UtmCorrection.
        /// </summary>
        public static string UtmCorrection {
            get {
                return ResourceManager.GetString("UtmCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UtmMax.
        /// </summary>
        public static string UtmMax {
            get {
                return ResourceManager.GetString("UtmMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value not selected, or not correct.
        /// </summary>
        public static string ValueIsNotGood {
            get {
                return ResourceManager.GetString("ValueIsNotGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The value &apos;{0}&apos; is not an integer.
        /// </summary>
        public static string ValueIsNotInteger {
            get {
                return ResourceManager.GetString("ValueIsNotInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value of manually entered parameter.
        /// </summary>
        public static string ValueOfManuallyEnteredParam {
            get {
                return ResourceManager.GetString("ValueOfManuallyEnteredParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Work with assembly protocol.
        /// </summary>
        public static string WorkWithAssemblyProtocol {
            get {
                return ResourceManager.GetString("WorkWithAssemblyProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Work with comments.
        /// </summary>
        public static string WorkWithComments {
            get {
                return ResourceManager.GetString("WorkWithComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Work with device references.
        /// </summary>
        public static string WorkWithDeviceReferences {
            get {
                return ResourceManager.GetString("WorkWithDeviceReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Work with manually entered parameters.
        /// </summary>
        public static string WorkWithManualInputParams {
            get {
                return ResourceManager.GetString("WorkWithManualInputParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Work with params of assembly protocol.
        /// </summary>
        public static string WorkWithManualParamsOfAssemblyProtocol {
            get {
                return ResourceManager.GetString("WorkWithManualParamsOfAssemblyProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Work with value of manually entered parameter.
        /// </summary>
        public static string WorkWithValueOfManualInputParam {
            get {
                return ResourceManager.GetString("WorkWithValueOfManualInputParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wrong description.
        /// </summary>
        public static string WrongDescription {
            get {
                return ResourceManager.GetString("WrongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The parameter was not created. The thermal conditions of the measurements and the created parameter do not match..
        /// </summary>
        public static string WrongTermalConditions {
            get {
                return ResourceManager.GetString("WrongTermalConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The value &apos;{0}&apos; does not match the mask &apos;{1}&apos;..
        /// </summary>
        public static string WrongValueByMask {
            get {
                return ResourceManager.GetString("WrongValueByMask", resourceCulture);
            }
        }
    }
}
